apiVersion : apps/v1
kind: Deployment
metadata:
  name: "feb09-796c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "feb09-796c"
  template:
    metadata:
      labels:
        app: "feb09-796c"
    spec:
      containers:
        - name: "feb09-796c"
          image: "feb09acr.azurecr.io/feb09"
          ports:
          - containerPort: 80