apiVersion : apps/v1
kind: Deployment
metadata:
  name: "feb05-9c71"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "feb05-9c71"
  template:
    metadata:
      labels:
        app: "feb05-9c71"
    spec:
      containers:
        - name: "feb05-9c71"
          image: "pipelinefeb05.azurecr.io/feb05"
          ports:
          - containerPort: 80