apiVersion: v1
kind: Service
metadata:
    name: "feb05-9c71"
    labels:
        app: "feb05-9c71"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "feb05-9c71"